# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '1.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
# merge 왜안댕 ~~~

#from PyQt5 import QtCore, QtGui, QtWidgets

from dialog import *
from data_load import *
import json
from users_lesson_assign import *

# 시간표 창 만들기
class Ui_Timetable(QDialog):
    def __init__(self):
        super().__init__()
        self.get_init_data()
        self.setupUi()

    # 데이터 불러오기
    def get_init_data(self):
        global tool_button_arr, configData, horizontal_header_arr
        # 버튼 관련 설정
        tool_button_arr = [
            ["사용자 지정", "img/edit.png", 50, 50, self.lesson_assign],
            ["삭제", "img/delete.png", 50, 50, self.delete]
        ]

        # json load
        with open("info_type.json", "r") as info:
            configData = json.load(info)

        horizontal_header_arr = ['월', '화', '수', '목', '금']

    # 화면 출력
    def setupUi(self):
        self.setObjectName("Dialog")
        self.setFixedSize(1050, 700)

        # 테이블 위젯 설정( 시간표)
        self.tableWidget = QTableWidget(self)
        self.tableWidget.setGeometry(QRect(160, 100, 850, 530))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)

        # 시간대 표시
        for i in range(len(time_list)):
            row = self.tableWidget.rowCount()
            self.tableWidget.insertRow(row)
            item = QTableWidgetItem()
            self.tableWidget.setVerticalHeaderItem(i, item)
            item = self.tableWidget.verticalHeaderItem(i)
            # print(time_list[i])
            time_text = time_list[i][1]+ '-' + time_list[i][2]
            item.setText(time_text)

        # 요일 입력
        for i in range(len(horizontal_header_arr)):
            item = QTableWidgetItem()
            self.tableWidget.setHorizontalHeaderItem(i, item)
            item = self.tableWidget.horizontalHeaderItem(i)
            item.setText(horizontal_header_arr[i])
            self.tableWidget.horizontalHeader().setSectionResizeMode(i, QHeaderView.Stretch)

        # 데이터 배치
        #강의ID	분반	교수명	강좌명	요일	시간ID	강의실명	대상학과	년도	학기
        # 월 수 -> [][0], [][2]
        # 화 목 -> [][1], [][3]
        # 금 -> [][4]
        # 9:00 -> [1][]

        # lesson_assign_list.append(['MA15642', 2, '최영준', '복소변수', '월, 수', '0,1,2', '607-208', '수학과2', 2022, 1])
        # print(lesson_assign_list)

        # 문제 2 : 합쳐져서 시간표가 안나옴
        for i in range(5):
            for j in range(18):
                self.tableWidget.setItem(j, i, QTableWidgetItem(""))

        # pre = ""
        # for i in range(len(lesson_assign_list)):
        #     txt = ""
        #     for j in lesson_assign_list[i][6].split(","): #12,13,14,15,16
        #         if self.tableWidget.item(int(j),0).text() != "":
        #             pre = self.tableWidget.item(int(j),0).text() + "\n"
        #         txt = pre + lesson_assign_list[i][1] + "(" + lesson_assign_list[i][2] + ")"
        #         if "월" in lesson_assign_list[i][5]:
        #             self.tableWidget.setItem(int(j),0,QTableWidgetItem(txt))
        #         if "화" in lesson_assign_list[i][5]:
        #             self.tableWidget.setItem(int(j),1,QTableWidgetItem(txt))
        #         if "수" in lesson_assign_list[i][5]:
        #             self.tableWidget.setItem(int(j),2,QTableWidgetItem(txt))
        #         if "목" in lesson_assign_list[i][5]:
        #             self.tableWidget.setItem(int(j),3,QTableWidgetItem(txt))
        #         if "금" in lesson_assign_list[i][5]:
        #             self.tableWidget.setItem(int(j),4,QTableWidgetItem(txt))





        # 테이블 위젯 행렬 사이즈 조절
        self.tableWidget.verticalHeader().setDefaultSectionSize(60)

        # 라벨 설정
        self.label = QLabel(self) # 학년도
        self.label.setObjectName("label")
        self.label.setGeometry(QRect(0, 10, 1050, 80))
        self.label.setAlignment(Qt.AlignCenter)
        global_funtion.fontSetting(self, self.label, "8H", 24, " ")
        label_text = str(year_str) + '학년도 ' + str(semester_str) + '학기'
        self.label.setText(label_text)

        # 버튼 설정
        self.verticalLayoutWidget = QWidget(self)
        self.verticalLayoutWidget.setGeometry(QRect(60, 80, 160, 420))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        # 버튼 생성
        for i in range(len(tool_button_arr)):
            self.toolButton = QToolButton(self.verticalLayoutWidget)
            global_funtion.tool_button_setting_widget(self, self.toolButton, self.verticalLayout, tool_button_arr[i])

        # 텍스트 출력
        self.retranslateUi()
        QMetaObject.connectSlotsByName(self)

        self.page_data()
        self.jsonload()

    def retranslateUi(self):
        _translate = QCoreApplication.translate
        self.setWindowTitle(_translate("Dialog", "강의 배정"))


    def page_data(self):
        global data, label_col
        data=[]
        if configData['info_type'] == "lesson_assign":
            data=lesson_assign_list
            label_col = lesson_assign_list_col

    def jsonload(self):
        global configData
        with open("info_type.json", "r") as info:
            configData = json.load(info)


    def lesson_assign(self):
        a = Ui_Lesson_Assign()
        a.exec_()

    def delete(self):
        print('삭제')

if __name__ == "__main__":
    import sys
    app = QApplication(sys.argv)
    Dialog = QDialog()
    ui = Ui_Dialog()
    ui.setupUi()
    ui.show()
    app.exec_()
